services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: pipeline_user
      POSTGRES_PASSWORD: pipeline_pass
      POSTGRES_DB: pipeline_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pipeline_user -d pipeline_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # etl:
  #   build:
  #     context: .
  #     dockerfile: etl/Dockerfile
  #   depends_on:
  #     db:
  #       condition: service_healthy

  ingest:
    build:
      context: .
      dockerfile: Dockerfile.ingest
    # Add a memory limit to prevent the container from being killed
    mem_limit: 1g
    command: >
      --user=pipeline_user
      --password=pipeline_pass 
      --host=postgres_db
      --port=5432 
      --db=pipeline_db
      --table_name=green_taxi_trips
      --url=https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2021-01.parquet
    depends_on:
      db:
        condition: service_healthy


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db_data:
